=== kb-dk/cdrip-robot/samples/Joblist 0.10.dtd
<!ELEMENT JOBLIST (CHARGELIST, BLOCK*)>

<!ELEMENT CHARGELIST (MAGAZINE*)>
<!ELEMENT MAGAZINE (PACKAGEID, MAGAZINESLOT*)>
<!ATTLIST MAGAZINE 
	num	CDATA #REQUIRED
>
<!ELEMENT PACKAGEID (#PCDATA)>
<!ELEMENT MAGAZINESLOT (CDNAME, JUKEBOXSLOT)>
<!ATTLIST MAGAZINESLOT 
	num	CDATA #REQUIRED
>
<!ELEMENT CDNAME (#PCDATA)>
<!ELEMENT JUKEBOXSLOT EMPTY>
<!ATTLIST JUKEBOXSLOT 
  num CDATA #REQUIRED
>

<!ELEMENT BLOCK (OUTPUT*)>
<!ELEMENT OUTPUT (NAME, INPUT)>
<!ELEMENT NAME (#PCDATA)>
<!ATTLIST NAME
  format CDATA #IMPLIED
>
<!ELEMENT INPUT (NAME)>
<!ATTLIST INPUT
  format CDATA #REQUIRED
  mode CDATA #REQUIRED
>

=== kb-dk/cdrip-robot/samples/jobfile_627.job.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- Joblist Version 0.10-->
<!DOCTYPE JOBLIST SYSTEM "Joblist 0.10.dtd">
<JOBLIST>
<CHARGELIST>

<MAGAZINE num="1">
<PACKAGEID>06000000293755</PACKAGEID>
<MAGAZINESLOT num="1">
<CDNAME></CDNAME>
<JUKEBOXSLOT num="101"/>
</MAGAZINESLOT>
<MAGAZINESLOT num="2">
<CDNAME></CDNAME>
<JUKEBOXSLOT num="102"/>
</MAGAZINESLOT>
<MAGAZINESLOT num="3">
<CDNAME></CDNAME>
<JUKEBOXSLOT num="103"/>
</MAGAZINESLOT>
<MAGAZINESLOT num="4">
<CDNAME></CDNAME>
<JUKEBOXSLOT num="104"/>
</MAGAZINESLOT>
<MAGAZINESLOT num="5">
<CDNAME></CDNAME>
<JUKEBOXSLOT num="105"/>
</MAGAZINESLOT>
</MAGAZINE>

</CHARGELIST>
<BLOCK>
<OUTPUT>
<NAME format="BWFTMP">208046/track.wav</NAME>
<INPUT format="CD" mode="auto">
<NAME>101</NAME>
</INPUT>
</OUTPUT>
</BLOCK>
<BLOCK>
<OUTPUT>
<NAME format="BWFTMP">208047/track.wav</NAME>
<INPUT format="CD" mode="auto">
<NAME>102</NAME>
</INPUT>
</OUTPUT>
</BLOCK>
<BLOCK>
<OUTPUT>
<NAME format="BWFTMP">208048/track.wav</NAME>
<INPUT format="CD" mode="auto">
<NAME>103</NAME>
</INPUT>
</OUTPUT>
</BLOCK>
<BLOCK>
<OUTPUT>
<NAME format="BWFTMP">208049/track.wav</NAME>
<INPUT format="CD" mode="auto">
<NAME>104</NAME>
</INPUT>
</OUTPUT>
</BLOCK>
<BLOCK>
<OUTPUT>
<NAME format="BWFTMP">208050/track.wav</NAME>
<INPUT format="CD" mode="auto">
<NAME>105</NAME>
</INPUT>
</OUTPUT>
</BLOCK>
</JOBLIST>
